#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        ICubeNS1130CU.py
#
#  Project :     iCubeNS1130CU
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      sergey.v.babenkov$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["ICubeNS1130CU", "ICubeNS1130CUClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(ICubeNS1130CU.additionnal_import) ENABLED START -----#
from ctypes import *
import time
import threading
import numpy as np
import struct
import io
import os
import pdb
#import tifffile
Modes = {
    0:"320x240",
    1:"640x480",
    2:"752x480",
    3:"800x600",
    4:"1024x768",
    5:"1280x1024",
    6:"1600x1200",
    7:"2048x1536",
    8:"2592x1944",
    9:"3840x2748"
}
buffSize = {
    0:230400,
    1:921600,
    2:1082880,
    3:1440000,
    4:2359296,
    5:3932160,
    6:5760000,
    7:9437184,
    8:15116544,
    9:31656960
}

iCube_response_code = {
    1:"IC_ERROR",
    0:"IC_SUCCESS",
    -1:"IC_IF_NOT_OPEN",
    -2:"IC_WRONG_PARAM",
    -3:"IC_OUT_OF_MEMORY",
    -4:"IC_ALREADY_DONE",
    -5:"IC_WRONG_CLOCK_VAL",
    -6:"IC_COMLIB_INIT",
    -7:"IC_NOT_IF_STARTED",
}

from PIL import Image, ImageChops
#----- PROTECTED REGION END -----#	//	ICubeNS1130CU.additionnal_import

# Device States Description
# No states for this device


class ICubeNS1130CU (PyTango.Device_4Impl):
    """iCubeNS1130CU"""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(ICubeNS1130CU.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        ICubeNS1130CU.init_device(self)
        #----- PROTECTED REGION ID(ICubeNS1130CU.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(ICubeNS1130CU.delete_device) ENABLED START -----#
        self.close()
        del self.attr_image_r_read
        del self.attr_image_g_read
        del self.attr_image_b_read
        del self.image_rgb
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_server_message_read = ""
        self.attr_Mode_read = 0
        self.attr_set_exposure_read = 0.0
        self.attr_Resolution_read = ""
        self.attr_save_image_trg_read = False
        self.attr_image_saved_check_read = 0.0
        self.attr_save_dir_read = ""
        self.attr_save_name_read = ""
        self.attr_file_prefix_read = 0
        self.attr_Camra_name_read = ""
        self.attr_icube_response_read = 0
        self.attr_camera_error_read = ""
        self.attr_Exposure_read = 0.0
        self.attr_image_r_read = [[0]]
        self.attr_image_g_read = [[0]]
        self.attr_image_b_read = [[0]]
        #----- PROTECTED REGION ID(ICubeNS1130CU.init_device) ENABLED START -----#
        #self.so_file = '/home/sergey/bin/TangoServers/iCube/test.so'
        #pdb.set_trace()
        print("Python {:s} on {:s}\n".format(sys.version, sys.platform))        
        self.iCube_response=0
        self.icube=CDLL('/usr/lib/libNETUSBCAM.so.0.0.0')
        self.camera = CDLL('/home/user/Git/iCubeNS1130CU/test.so')        

        self.connect()
        self.img_accu=np.array([[[0]]])

        self.write_selected=0
        #self.connect_old()
        self.check_camera_mode_trg=True
        self.check_camera_exp_trg=True
        self.streaming_trg=False
        self.accu_trig=False
        self.image_rgb=[[[0]]]
        if not 'image_accu' in dir(self):
            self.image_accu = threading.Thread(target=self.accu)
            self.image_accu.setDaemon(True)
            self.image_accu.start()    
        if not 'save_image' in dir(self):
            self.save_image = threading.Thread(target=self.save)
            self.save_image.setDaemon(True)
            self.save_image.start() 
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(ICubeNS1130CU.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.always_executed_hook

    # -------------------------------------------------------------------------
    #    ICubeNS1130CU read/write attribute methods
    # -------------------------------------------------------------------------
    
    def write_open_close(self, attr):
        self.debug_stream("In write_open_close()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(ICubeNS1130CU.open_close_write) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.open_close_write
        
    def read_server_message(self, attr):
        self.debug_stream("In read_server_message()")
        #----- PROTECTED REGION ID(ICubeNS1130CU.server_message_read) ENABLED START -----#
        attr.set_value(self.attr_server_message_read)
        
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.server_message_read
        
    def read_Mode(self, attr):
        self.debug_stream("In read_Mode()")
        #----- PROTECTED REGION ID(ICubeNS1130CU.Mode_read) ENABLED START -----#
        #pdb.set_trace()
        if self.get_state() == PyTango.DevState.ON and self.check_camera_mode_trg==True:
            mode = c_uint()
            self.attr_icube_response_read=self.icube.NETUSBCAM_GetMode(0,byref(mode))
            if self.attr_icube_response_read!=0:
                self.set_state(PyTango.DevState.FAULT)
                self.attr_camera_error_read="Read Mode:"+iCube_response_code[self.attr_icube_response_read]
            else:
                self.attr_Mode_read=mode.value
                self.attr_Resolution_read=Modes[self.attr_Mode_read]
            self.check_camera_mode_trg=False
        attr.set_value(self.attr_Mode_read)
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.Mode_read
        
    def write_Mode(self, attr):
        self.debug_stream("In write_Mode()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(ICubeNS1130CU.Mode_write) ENABLED START -----#
        if self.get_state() == PyTango.DevState.ON:
            print (data, type(data))
            self.attr_icube_response_read=self.icube.NETUSBCAM_SetMode(0,data)
            if self.attr_icube_response_read!=0:
                self.set_state(PyTango.DevState.FAULT)
                self.attr_camera_error_read="Set Mode:"+iCube_response_code[self.attr_icube_response_read]
            self.check_camera_mode_trg=True
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.Mode_write
        
    def write_start_stop_streaming(self, attr):
        self.debug_stream("In write_start_stop_streaming()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(ICubeNS1130CU.start_stop_streaming_write) ENABLED START -----#
        if self.get_state() == PyTango.DevState.ON:
            if data==True:
                self.img_buffer  = create_string_buffer(buffSize[self.attr_Mode_read])
                self.mypointer = addressof(self.img_buffer)
                self.camera._Z12set_callbackiPv.argtypes = [c_int, c_void_p]
                callback=self.camera._Z12set_callbackiPv(self.iCube_response, self.mypointer)
                streaming=self.camera._Z15start_streamingi(self.iCube_response)           
                if callback==0 and streaming==0:
                    
                    self.streaming_trg=True
            elif data==False:
                self.streaming_trg=False
                self.camera._Z14stop_streamingi(self.iCube_response)
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.start_stop_streaming_write
        
    def read_set_exposure(self, attr):
        self.debug_stream("In read_set_exposure()")
        #----- PROTECTED REGION ID(ICubeNS1130CU.set_exposure_read) ENABLED START -----#

        #pdb.set_trace()
        if self.get_state() == PyTango.DevState.ON and self.check_camera_exp_trg==True:
            exposure = c_float()#create_string_buffer(20)
            self.attr_icube_response_read=self.icube.NETUSBCAM_GetExposure(0, byref(exposure))
            if self.attr_icube_response_read!=0:
                self.set_state(PyTango.DevState.FAULT)
                self.attr_camera_error_read="Read Exposure:"+iCube_response_code[self.attr_icube_response_read]
            else:
                self.attr_set_exposure_read=exposure.value
            self.check_camera_exp_trg==False
        attr.set_value(self.attr_set_exposure_read)
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.set_exposure_read
        
    def write_set_exposure(self, attr):
        self.debug_stream("In write_set_exposure()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(ICubeNS1130CU.set_exposure_write) ENABLED START -----#
        if self.get_state() == PyTango.DevState.ON:
            #pdb.set_trace()
            print (data, type(data))
            self.attr_icube_response_read=self.icube.NETUSBCAM_SetExposure(0,data)
            if self.attr_icube_response_read!=0:
                self.set_state(PyTango.DevState.FAULT)
            else:
                self.check_camera_exp_trg=True
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.set_exposure_write
        
    def read_Resolution(self, attr):
        self.debug_stream("In read_Resolution()")
        #----- PROTECTED REGION ID(ICubeNS1130CU.Resolution_read) ENABLED START -----#
        attr.set_value(self.attr_Resolution_read)
        
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.Resolution_read
        
    def read_save_image_trg(self, attr):
        self.debug_stream("In read_save_image_trg()")
        #----- PROTECTED REGION ID(ICubeNS1130CU.save_image_trg_read) ENABLED START -----#
        attr.set_value(self.attr_save_image_trg_read)
        
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.save_image_trg_read
        
    def write_save_image_trg(self, attr):
        self.debug_stream("In write_save_image_trg()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(ICubeNS1130CU.save_image_trg_write) ENABLED START -----#
        self.attr_save_image_trg_read=data
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.save_image_trg_write
        
    def read_image_saved_check(self, attr):
        self.debug_stream("In read_image_saved_check()")
        #----- PROTECTED REGION ID(ICubeNS1130CU.image_saved_check_read) ENABLED START -----#
        attr.set_value(self.attr_image_saved_check_read)
        
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.image_saved_check_read
        
    def read_save_dir(self, attr):
        self.debug_stream("In read_save_dir()")
        #----- PROTECTED REGION ID(ICubeNS1130CU.save_dir_read) ENABLED START -----#
        attr.set_value(self.attr_save_dir_read)
        
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.save_dir_read
        
    def write_save_dir(self, attr):
        self.debug_stream("In write_save_dir()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(ICubeNS1130CU.save_dir_write) ENABLED START -----#
        self.attr_save_dir_read=data
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.save_dir_write
        
    def read_save_name(self, attr):
        self.debug_stream("In read_save_name()")
        #----- PROTECTED REGION ID(ICubeNS1130CU.save_name_read) ENABLED START -----#
        attr.set_value(self.attr_save_name_read)
        
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.save_name_read
        
    def write_save_name(self, attr):
        self.debug_stream("In write_save_name()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(ICubeNS1130CU.save_name_write) ENABLED START -----#
        self.attr_save_name_read=data
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.save_name_write
        
    def read_file_prefix(self, attr):
        self.debug_stream("In read_file_prefix()")
        #----- PROTECTED REGION ID(ICubeNS1130CU.file_prefix_read) ENABLED START -----#
        attr.set_value(self.attr_file_prefix_read)
        
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.file_prefix_read
        
    def write_file_prefix(self, attr):
        self.debug_stream("In write_file_prefix()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(ICubeNS1130CU.file_prefix_write) ENABLED START -----#
        self.attr_file_prefix_read=data
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.file_prefix_write
        
    def read_Camra_name(self, attr):
        self.debug_stream("In read_Camra_name()")
        #----- PROTECTED REGION ID(ICubeNS1130CU.Camra_name_read) ENABLED START -----#
        attr.set_value(self.attr_Camra_name_read)
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.Camra_name_read
        
    def read_icube_response(self, attr):
        self.debug_stream("In read_icube_response()")
        #----- PROTECTED REGION ID(ICubeNS1130CU.icube_response_read) ENABLED START -----#
        attr.set_value(self.attr_icube_response_read)
        
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.icube_response_read
        
    def read_camera_error(self, attr):
        self.debug_stream("In read_camera_error()")
        #----- PROTECTED REGION ID(ICubeNS1130CU.camera_error_read) ENABLED START -----#
        attr.set_value(self.attr_camera_error_read)
        
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.camera_error_read
        
    def read_Exposure(self, attr):
        self.debug_stream("In read_Exposure()")
        #----- PROTECTED REGION ID(ICubeNS1130CU.Exposure_read) ENABLED START -----#

        if self.get_state() == PyTango.DevState.ON and self.check_camera_exp_trg==True:
            exposure = c_float()#create_string_buffer(20)
            self.attr_icube_response_read=self.icube.NETUSBCAM_GetExposure(0, byref(exposure))
            if self.attr_icube_response_read!=0:
                self.set_state(PyTango.DevState.FAULT)
                self.attr_camera_error_read="Read Exposure:"+iCube_response_code[self.attr_icube_response_read]
            else:
                self.attr_Exposure_read=exposure.value
            self.check_camera_exp_trg==False
        attr.set_value(self.attr_Exposure_read)
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.Exposure_read
        
    def write_Exposure(self, attr):
        self.debug_stream("In write_Exposure()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(ICubeNS1130CU.Exposure_write) ENABLED START -----#
        if self.get_state() == PyTango.DevState.ON:
            print (data, type(data))
            exposure = c_float(round(data,3))
            print (exposure)
            self.attr_icube_response_read=self.icube.NETUSBCAM_SetExposure(0,exposure)
            print (self.attr_icube_response_read)
            if self.attr_icube_response_read!=0:
                self.set_state(PyTango.DevState.FAULT)
                self.attr_camera_error_read="Write Exposure:"+iCube_response_code[self.attr_icube_response_read]
            else:
                self.check_camera_exp_trg=True
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.Exposure_write
        
    def read_image_r(self, attr):
        self.debug_stream("In read_image_r()")
        #----- PROTECTED REGION ID(ICubeNS1130CU.image_r_read) ENABLED START -----#
        attr.set_value(self.attr_image_r_read)
        
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.image_r_read
        
    def read_image_g(self, attr):
        self.debug_stream("In read_image_g()")
        #----- PROTECTED REGION ID(ICubeNS1130CU.image_g_read) ENABLED START -----#
        attr.set_value(self.attr_image_g_read)
        
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.image_g_read
        
    def read_image_b(self, attr):
        self.debug_stream("In read_image_b()")
        #----- PROTECTED REGION ID(ICubeNS1130CU.image_b_read) ENABLED START -----#
        attr.set_value(self.attr_image_b_read)
        
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.image_b_read
        
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(ICubeNS1130CU.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.read_attr_hardware


    # -------------------------------------------------------------------------
    #    ICubeNS1130CU command methods
    # -------------------------------------------------------------------------
    

    #----- PROTECTED REGION ID(ICubeNS1130CU.programmer_methods) ENABLED START -----#
        
    def connect(self):
        self.iCube_response=self.icube.NETUSBCAM_Init()
        if self.iCube_response==0:
            self.set_state(PyTango.DevState.FAULT)
            self.attr_server_message_read="no device"
        elif self.iCube_response!=0:
            self.attr_icube_response_read=self.icube.NETUSBCAM_Open(0)
            if self.attr_icube_response_read!=0:
                self.set_state(PyTango.DevState.FAULT)
                self.attr_camera_error_read="camera error:"+iCube_response_code[self.attr_icube_response_read]
            else:
                self.set_state(PyTango.DevState.ON)
                self.attr_server_message_read=str(self.iCube_response)+" camera(s) found"
                str_buffer  = create_string_buffer(20)
                self.attr_icube_response_read=self.camera.NETUSBCAM_GetName(0, str_buffer,20)
                self.attr_Camra_name_read=str_buffer.value
                if self.attr_icube_response_read!=0:
                    self.attr_camera_error_read="camera error:"+iCube_response_code[self.attr_icube_response_read]
                else:
                    self.attr_camera_error_read=iCube_response_code[self.attr_icube_response_read]
                
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
                        
    def save(self):
        while True:
            time.sleep(1)
            if self.attr_save_image_trg_read==True:
                if self.attr_save_dir_read=="" or self.attr_save_name_read=="":
                    self.attr_server_message_read="Check file path!"
                else:
                    now=time.strftime("%Y_%m_%d", time.gmtime())
                    path=self.attr_save_dir_read+"/"+now
                    if not os.path.exists(path):
                        os.makedirs(path)
                    path+="/"+str(self.attr_file_prefix_read)+"_"+self.attr_save_name_read+"tiff"
                    x,y=Modes[self.attr_Mode_read].split("x")
                    imgSize=[int(x),int(y)]
                    img = Image.frombytes('RGB', imgSize, self.img_buffer_raw, 'raw')#, 'F;16')
                    img.save("test_python.tiff", compression="tiff_deflate", save_all=True)
                    #self.write_save_image_trg(False)
                self.attr_image_saved_check_read=True                
    def close(self):
        if self.iCube_response==0:
            self.accu_trig=False
            self.streaming_trg=False
            self.camera._Z14stop_streamingi(self.iCube_response)
            self.camera.close(self.iCube_response)
    def accu(self):
        while True:
            if self.get_state() == PyTango.DevState.ON and self.accu_trig==True:
                while self.accu_trig==True:                    
                    x,y=Modes[self.attr_Mode_read].split("x")
                    self.img_accu=np.array([[[0]*3]*int(y)]*int(x),dtype=np.uint32)
                    self.attr_image_r_read = np.array([[0]*int(y)]*int(x),dtype=np.uint32)
                    self.attr_image_g_read = np.array([[0]*int(y)]*int(x),dtype=np.uint32)
                    self.attr_image_b_read = np.array([[0]*int(y)]*int(x),dtype=np.uint32)
                    print (type(self.img_buffer))
                    self.img_accu=np.frombuffer(self.img_buffer.raw, dtype=np.uint8, count=-1).reshape(int(x), int(y), 3)
                    self.attr_memory_pointer_read=self.img_buffer
                    #print (self.img_accu.shape, self.attr_image_r_read.shape)
                    #self.attr_image_r_read = self.img_accu[:,:,0]
                    #self.attr_image_r_read = self.img_accu[:,:,1]
                    #self.attr_image_r_read = self.img_accu[:,:,2]
                    time.sleep(1)
                    
            time.sleep(1)
            
    def accu_image(self):
        while True:
            if self.get_state() == PyTango.DevState.ON and self.accu_trig==True:
                while self.accu_trig==True:
                    x,y=Modes[self.attr_Mode_read].split("x")
                    imgSize=[int(x),int(y)]
                    img = Image.frombytes('I', imgSize, self.img_buffer.raw, 'raw')#, 'F;16')
                    for i in range (self.attr_accu_time_read):
                        img=ImageChops.add(img, Image.frombytes('I', imgSize, self.img_buffer.raw, 'raw'), scale=1.0, offset=0)
                        print (i)
                        time.sleep(self.attr_accu_time_read)
                    img.save("test_python.tiff", compression="tiff_deflate", save_all=True)
                    #self.file_counter=PyTango.DeviceProxy("icube/usb/camera")
                    #self.file_counter.write_attribute("save_image_trg",True)
                    self.accu_trig=False
                    time.sleep(1)
                    
            time.sleep(1)
"""
        string_buffers = [create_string_buffer(20) for i in range(2)]
        pointers = (c_char_p*2)(*map(addressof, string_buffers))
        self.camera._Z4nameiPPc(self.iCube_response, pointers)
        results = [s.value for s in string_buffers]
        self.attr_Camra_name_read=results[0]
""" 
    #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.programmer_methods

class ICubeNS1130CUClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(ICubeNS1130CU.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.global_class_variables


    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        }


    #    Attribute definitions
    attr_list = {
        'open_close':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.WRITE]],
        'server_message':
            [[PyTango.DevString,
            PyTango.SCALAR,
            PyTango.READ]],
        'Mode':
            [[PyTango.DevLong,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'max value': "9",
                'min value': "0",
                'Memorized':"true"
            } ],
        'start_stop_streaming':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.WRITE]],
        'set_exposure':
            [[PyTango.DevFloat,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'max value': "630",
                'min value': "30",
            } ],
        'Resolution':
            [[PyTango.DevString,
            PyTango.SCALAR,
            PyTango.READ]],
        'save_image_trg':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        'image_saved_check':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'save_dir':
            [[PyTango.DevString,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'Memorized':"true"
            } ],
        'save_name':
            [[PyTango.DevString,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'Memorized':"true"
            } ],
        'file_prefix':
            [[PyTango.DevLong,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'Memorized':"true"
            } ],
        'Camra_name':
            [[PyTango.DevString,
            PyTango.SCALAR,
            PyTango.READ]],
        'icube_response':
            [[PyTango.DevLong,
            PyTango.SCALAR,
            PyTango.READ]],
        'camera_error':
            [[PyTango.DevString,
            PyTango.SCALAR,
            PyTango.READ]],
        'Exposure':
            [[PyTango.DevFloat,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        'image_r':
            [[PyTango.DevLong,
            PyTango.IMAGE,
            PyTango.READ, 1280, 1024]],
        'image_g':
            [[PyTango.DevLong,
            PyTango.IMAGE,
            PyTango.READ, 3000, 3000]],
        'image_b':
            [[PyTango.DevLong,
            PyTango.IMAGE,
            PyTango.READ, 3000, 3000]],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(ICubeNS1130CUClass, ICubeNS1130CU, 'ICubeNS1130CU')
        #----- PROTECTED REGION ID(ICubeNS1130CU.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	ICubeNS1130CU.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
